# Generated by Django 5.0.6 on 2024-06-06 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecode',
            name='expiration_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 6, 18, 41, 16, 257471, tzinfo=datetime.timezone.utc)),
        ),
    ]
