# Generated by Django 5.0.6 on 2024-06-11 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_phonecode_expiration_at_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecode',
            name='expiration_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 11, 13, 11, 57, 532442, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(unique=True, verbose_name='phone_username'),
        ),
    ]
