# Generated by Django 5.0.6 on 2024-06-11 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_phonecode_expiration_at_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='codeMeli',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='phonecode',
            name='expiration_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 11, 15, 4, 34, 354497, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
