# Generated by Django 5.0.6 on 2024-06-11 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_codemeli_alter_phonecode_expiration_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecode',
            name='expiration_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 11, 15, 26, 7, 875138, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
