# Generated by Django 5.0.6 on 2024-06-11 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_phonecode_expiration_at_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecode',
            name='expiration_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 11, 15, 34, 25, 308392, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
