# Generated by Django 5.0.6 on 2024-07-05 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_phonecode_expiration_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecode',
            name='expiration_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 5, 14, 58, 18, 369883, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
