# Generated by Django 5.0.6 on 2024-07-17 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_phonecode_expiration_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecode',
            name='expiration_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 9, 25, 57, 844409, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
