# Generated by Django 5.0.6 on 2024-07-17 09:35

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_phonecode_expiration_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecode',
            name='expiration_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 9, 40, 47, 439917, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.CreateModel(
            name='Adresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ostan', models.CharField(max_length=40)),
                ('shahr', models.CharField(max_length=40)),
                ('adress', models.CharField(max_length=100)),
                ('postalCode', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
