# Generated by Django 5.0.6 on 2024-07-17 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_phonecode_expiration_at_adresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecode',
            name='expiration_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 9, 42, 2, 363115, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
