# Generated by Django 5.0.6 on 2024-07-19 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_phonecode_expiration_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shaba',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='phonecode',
            name='expiration_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 14, 37, 2, 854213, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
