# Generated by Django 5.0.6 on 2024-07-17 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='address_id',
        ),
    ]
