# Generated by Django 5.0.6 on 2024-07-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_address_order_address_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_id',
            new_name='address',
        ),
    ]
