# Generated by Django 5.0.6 on 2024-07-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_address_id_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='extraText',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
